#! /usr/bin/env bash

# $Header: /u/u3/gcmpack/MITgcm_contrib/test_scripts/halem/test_halem_auden,v 1.1 2003/12/04 20:30:17 edhill Exp $

#  Ed Hill

#  Testing script designed to be run on halem.  Note that halem
#  doesn't seem to have a working cron system for ordinary users -- I
#  got multiple errors.

echo -n "Creating the MITgcm tar-ball ..."
cd /u/u3/edhill/testing/
test -e halem  &&  rm -rf halem
mkdir halem
cd halem
cvs co MITgcm_verif_basic > /dev/null 2>&1
tar -czf MITgcm.tar.gz ./MITgcm
echo "  done"

echo -n "Copying it to halem ..."
scp MITgcm.tar.gz halem.gsfc.nasa.gov:/u1/edhill/
echo "  done"

echo "Executing the test_halem script on halem ..."
ssh halem.gsfc.nasa.gov '/usr/ulocal/bin/bash /u1/edhill/bin/test_halem'
echo "  done"
