#!/bin/csh

# LoadLeveler batch commands that are used if this script is submitted to
#   the share batch queue:
#@output=out
#@error=err
#@class=share

#@job_type=parallel
#@node=1
#@network.MPI=csss,shared,us
#@queue

cd /ptmp/edhill/tmp/MITgcm/verification

cat <<EOF > tr_run_command
#! /usr/bin/env bash

make output.txt
cp -f STDOUT.0000 output.txt

EOF

chmod a+x ./tr_run_command

./testreport -command ../../tr_run_command  -make gmake -of=../tools/build_options/sp4 -a edhill@mitgcm.org


