#! /usr/bin/env bash

#  Download and run the MITgcm model verification suite on
#  bluesky.ucar.edu with load leveler but without using MPI.

echo ":pserver:cvsanon@mitgcm.org:/u/gcmpack Ah<Zy=0=" > ~/.cvspass

cd /ptmp/edhill

DIR=tmp
test -e $DIR  &&  rm -rf $DIR
mkdir $DIR
cd $DIR

cvs -d :pserver:cvsanon@mitgcm.org:/u/gcmpack co MITgcm_verif_basic

/ssg/loadl/bin/llsubmit ~/bin/bluesky_ll_testreport_all


