#!/bin/bash
#
#PBS -q short
#PBS -N run_tst_ifc
#PBS -l nodes=1:ppn=6:sandy
#PBS -e /home/jm_c/test_svante/output/run_tst_ifc.stderr
#PBS -o /home/jm_c/test_svante/output/run_tst_ifc.stdout
##PBS  -j oe

# $Header: /u/gcmpack/MITgcm_contrib/test_scripts/svante/run_tst_ifc.pbs,v 1.4 2015/11/08 17:30:45 jmc Exp $

if test -f /etc/profile.d/modules.sh ; then
    . /etc/profile.d/modules.sh
fi
# Note: added "limit stacksize unlimited" in file "~/.tcshrc"
# to pass big test (the 2 fizhi-cs-* test & adjoint tests) with MPI

umask 0022
#- to get case insensitive "ls" (and order of tested experiments)
export LC_ALL="en_US.UTF-8"
echo " running on: "`hostname`

dNam='svante'
HERE="$HOME/test_${dNam}"
OUTP="$HERE/output"; SavD="$HERE/send"
SEND="ssh svante $SavD/mpack"
TST_DISK="/net/fs09/d0/jm_c"
TST_DIR="$TST_DISK/test_${dNam}"

cd $TST_DISK ; pwd
if test -d $TST_DIR ; then
  echo "start from TST_DIR='$TST_DIR' at: "`date`
else
  echo "ERROR: missing directory \"$TST_DIR\""
  exit 1
fi

sfx='ifc'

module add intel
module add mvapich2
OPTFILE="../tools/build_options/linux_amd64_ifort11"
options="-MPI 6 -ro"
#options="$options -t hs94.cs-32x32x5"
#EXE="mpirun -v -all-local -np TR_NPROC ./mitgcmuv"

dInWeek=`date +%a`
if test "x$dInWeek" = xSun ; then
  options="$options -fast"
#else
# options="$options -devel"
fi

#- need this to get "staf":
#export PATH="$PATH:$HOME/bin"

gcmDIR="MITgcm_$sfx"
cd $TST_DIR

#- change dir to $gcmDIR/verification dir:
if test -e $gcmDIR/verification ; then
  echo " dir $gcmDIR/verification exist"
  cd $gcmDIR/verification
else
  echo "no dir: $gcmDIR/verification => exit"
  exit
fi

 echo ./testreport $options -of $OPTFILE -odir ${dNam}-$sfx \
    -send \"$SEND\" -sd $SavD -a jmc@mitgcm.org
 ./testreport $options -of $OPTFILE -odir ${dNam}-$sfx \
    -send "$SEND" -sd $SavD -a jmc@mitgcm.org


 echo ''
#echo ../tools/do_tst_2+2 -mpi -exe \"$EXE\" -o ${dNam}-$sfx \
#../tools/do_tst_2+2 -mpi -exe "$EXE" -o ${dNam}-$sfx \
 echo ../tools/do_tst_2+2 -mpi -o ${dNam}-$sfx \
    -send \"$SEND\" -sd $SavD -a jmc@mitgcm.org
 ../tools/do_tst_2+2 -mpi -o ${dNam}-$sfx \
    -send "$SEND" -sd $SavD -a jmc@mitgcm.org

exit
