#! /usr/bin/env bash

# $Header: /u/gcmpack/MITgcm_contrib/test_scripts/other/test_update_local,v 1.2 2023/06/04 14:04:15 jmc Exp $
# $Name:  $

gcmDIR="MITgcm"
logFile='check_update.log'
CronTabFile='crontab_jmc'

if test -f git_Hash ; then mv git_Hash prevHash ; fi
if test -e $gcmDIR/.git/config ; then
  ( cd $gcmDIR ; git checkout master > /dev/null 2>&1 )
  ( cd $gcmDIR ; git pull > /dev/null ) ; retv=$?
  if  test $retv = 0 ; then
    ( cd $gcmDIR ; git rev-parse HEAD > ../git_Hash )
  else
    echo "== running: \""`basename $0`"\" on:" `date` >> $logFile
    echo "  'git pull' in $gcmDIR fail (return val=$retv) => no new 'git_Hash'" >> $logFile
  fi
fi

cronStuff=`grep -v '^#' $CronTabFile | grep 'test_local .*>' | sed 's/^.*test_local //' | sed 's/>*\&//'`
pp=0
for xx in $cronStuff ; do
  #echo " xx='${xx}'"
  if test $pp = 0 ; then
    #-- set pair firt param:
    pp=$xx
  else
    #-- set pair second param:
    #echo -n " pair of arg: pp='${pp}' & xx='${xx}'"
    namF=${xx}
    savF=`echo $namF | sed 's/_[0-9]*$/_/'`$pp
    #echo " ; savF='${savF}'"
    if test -e $namF ; then
      #ls -l $namF
      if test -s $namF ; then : else
        #echo "mv $namF $savF"
        mv -f $namF $savF
      fi
    #else echo " no file: $namF"
    fi
    #-- reset pair firt param:
    pp=0
  fi
done

exit
#--------------------------
sfx='test_local.outp'
list='tap gfort'

n=0
for tt in $list
do
  namF=${sfx}'_'$n
  savF=${sfx}'_'$tt
  if test -e $namF ; then
    #ls -l $namF
    if test -s $namF ; then : else
      #echo "mv $namF $savF"
      mv -f $namF $savF
    fi
  #else echo " no file: $namF"
  fi
  n=`expr $n + 1`
done
#echo '<-- done' ; ls -l ${sfx}_*
