#! /usr/bin/env bash

# $Header:  $
# $Name:  $

echo 'source ~jmc/bin/intel_64.csh'
source ~jmc/bin/intel_64.sh
tst_list='mp2 ur4'
#tst_list='ur4'
#tst_list='mp2'

for tt in $tst_list
do

  echo "=========================================================================="
  set -x
  rm -f tr_clean_$tt.log
  #- cleanup previous restart:
  ( cd MITgcm_$tt/verification ; ../tools/do_tst_2+2 -clean > ../../tr_clean_$tt.log 2>&1 )
  #- cleanup previous test:
  ( cd MITgcm_$tt/verification ; testreport -clean >> ../../tr_clean_$tt.log 2>&1 )

  set +x
  echo ""

  echo "=========================================================================="
  set -x
  ( cd MITgcm_$tt ; cvs update -P -d  >> ../tr_clean_$tt.log 2>&1 )
  set +x
  echo ""

  echo "=========================================================================="

  mv -f tr_run_$tt.log tr_run_$tt.log_bak
  cd MITgcm_$tt/verification

  date
  # verbose mode:
  set -x
  pwd

if test $tt = 'mp2' ; then

  export OMP_NUM_THREADS=2
  export KMP_STACKSIZE=400m

  testreport -MPI 2 -mth -of ../tools/build_options/linux_amd64_ifort+mpi_loc \
   -command='mpirun -v -np TR_NPROC ./mitgcmuv' \
   -a jmc@mitgcm.org -nc > ../../tr_run_$tt.log 2>&1

  #unset echo
  sed -n "/ email /,$ p" ../../tr_run_$tt.log

  #- test restart:
  echo '' >> ../../tr_run_$tt.log 2>&1
  ../tools/do_tst_2+2 -mpi -exe 'mpirun -v -np TR_NPROC ./mitgcmuv' \
   -a jmc@mitgcm.org >> ../../tr_run_$tt.log 2>&1

fi

if test $tt = 'ur4' ; then

  testreport -MPI 3 -ur4 -of ../../linux_amd64_ifort+mpi_chk \
   -nc -dd -nr > ../../tr_run_$tt.log 2>&1

  set +x
  echo '' ; echo ' remove */build/*.o */mitgcmuv'
  /bin/rm -f */build/*.o
  /bin/rm -f */build/mitgcmuv
  echo ''
  set -x

  testreport -MPI 3 -ur4 -of ../../linux_amd64_ifort+mpi_chk \
   -match 5 -command='mpirun -v -np TR_NPROC ./mitgcmuv' \
   -a jmc@mitgcm.org -q >> ../../tr_run_$tt.log 2>&1

  sed -n "/ email /,$ p" ../../tr_run_$tt.log

  #- test restart:
  echo '' >> ../../tr_run_$tt.log 2>&1
  ../tools/do_tst_2+2 -mpi -exe 'mpirun -v -np TR_NPROC ./mitgcmuv' \
   -a jmc@mitgcm.org >> ../../tr_run_$tt.log 2>&1

fi

  set +x
  cd ../..

done
