#! /usr/bin/env bash

# $Header: /u/gcmpack/MITgcm_contrib/test_scripts/other/testing_loc,v 1.21 2015/06/20 00:25:01 jmc Exp $
# $Name:  $

if test $# = 0 ; then
  echo 'need 1 argument'
  exit
else
  if test $1 = ifort ; then
#   tst_list='iadm imp2 iur4'
    tst_list='iad4 imp2 iur4'
    dd1=`date +%d -d "1 day"`
#   if test $dd1 != '01' ; then echo 'not last day of month'; exit ; fi
  elif test $1 = gfort ; then
#   tst_list='gadm gads gmp2 gmpi gfo g77'
    tst_list='gadm gads gmp2 gfo'
  elif test $1 = gfor4 ; then
    tst_list='gad4 gmp4 gfo4 g77'
  else
    tst_list=$*
  fi
fi
  echo "run: \""`basename $0` $*"\" on:" `date`
  echo " tst_list='$tst_list'"

#- to get ~/bin in the patch (for staf) when run on cron:
if [ -d ~/bin ]; then
  echo 'add ~/bin to $PATH'
  export PATH=$PATH:~/bin
fi
#- to get case insensitive "ls" (and order of tested experiments)
#export LC_ALL="en_US.UTF-8"
#- Turn off stack limit for FIZHI & AD-tests
ulimit -s unlimited
#- method to acces CVS:
cmdCVS='cvs -d :pserver:cvsanon@mitgcm.org:/u/gcmpack -q'

#-- for now, cannot mix ifort/gfortran tests:
gfort=1
for tt in $tst_list
do
  echo $tt | grep '^g' > /dev/null 2>&1 ; retv=$?
  if   [ $retv -eq 0 -a $gfort -ge 1 ] ; then gfort=2
  elif [ $retv -ne 0 -a $gfort -le 1 ] ; then gfort=0
  else echo 'cannot mix ifort/gfortran' ; exit
  fi
done
if [ $gfort -eq 0 ] ; then
   echo 'source ~jmc/bin/intel_v14.sh'
   source ~jmc/bin/intel_v14.sh
  #echo 'source ~jmc/bin/intel_v15.sh'
  #source ~jmc/bin/intel_v15.sh
fi
if [ $gfort -eq 2 ] ; then
   echo 'source ~jmc/bin/openmpi.sh'
   source ~jmc/bin/openmpi.sh
fi

#--------------------------------------------------------------------
for tt in $tst_list
do

  echo "=========================================================================="
# set -x
  rm -f tr_clean_$tt.log
  echo $tt | grep '^.ad' > /dev/null 2>&1 ; fwd=$?
  echo " testing tt= $tt , fwd= $fwd"
 if test -d MITgcm_$tt/verification ; then
 #- cleaning previous testreport run and updating the code:
  if [ $fwd -eq 0 ] ; then
   set -x
  #- cleanup previous test:
   ( cd MITgcm_$tt/verification ; ./testreport -adm -clean > ../../tr_clean_$tt.log 2>&1 )
   set +x
  else
   set -x
  #- cleanup previous restart:
   ( cd MITgcm_$tt/verification ; ../tools/do_tst_2+2 -clean > ../../tr_clean_$tt.log 2>&1 )
  #- cleanup previous test:
   ( cd MITgcm_$tt/verification ; ./testreport -clean >> ../../tr_clean_$tt.log 2>&1 )
   set +x
  fi
  if [ $gfort -eq 0 ] ; then
    echo ' remove all Makefile_syntax and do "cvs update -P -d"' >> tr_clean_$tt.log
    ( cd MITgcm_$tt/verification ; rm -f */build/Makefile_syntax )
  else
    echo " run '$cmdCVS update -P -d'"  >> tr_clean_$tt.log
  fi
  echo ""

  echo "=========================================================================="
  set -x
  #- update the code:
  ( cd MITgcm_$tt ; $cmdCVS update -P -d  >> ../tr_clean_$tt.log 2>&1 )
  set +x
 else
 #- download new code:
  echo " run '$cmdCVS co -P -d  MITgcm_$tt MITgcm'"  >> tr_clean_$tt.log
  echo "=========================================================================="
  set -x
    $cmdCVS co -P -d  MITgcm_$tt MITgcm >> tr_clean_$tt.log 2>&1
  set +x
 fi
  echo ""
  echo "=========================================================================="

 if test -d MITgcm_$tt/verification ; then
  if test -e tr_run_$tt.log ; then mv -f tr_run_$tt.log tr_run_$tt.log_bak ; fi
  cd MITgcm_$tt/verification

  date
  # verbose mode:
  set -x
  pwd
  test -e tr_out.txt && mv -f tr_out.txt tr_out.sav

case $tt in
'iadm' )

  ./testreport -MPI 3 -adm -of ../tools/build_options/linux_amd64_ifort11 \
   -devel -nc -ncad -repl_mk do_make_syntax.sh -obj -dd > ../../tr_run_$tt.log 2>&1
  echo '' >> ../../tr_run_$tt.log 2>&1

  ./testreport -MPI 3 -adm -of ../tools/build_options/linux_amd64_ifort11 \
   -devel -q -a jmc@mitgcm.org >> ../../tr_run_$tt.log 2>&1

  sed -n "/ email /,/^======== End of testreport / p" ../../tr_run_$tt.log
;;

'iad4' )

  ./testreport -MPI 3 -ur4 -adm -of ../tools/build_options/linux_amd64_ifort11 \
   -devel -nc -ncad -repl_mk do_make_syntax.sh -obj -dd > ../../tr_run_$tt.log 2>&1
  echo '' >> ../../tr_run_$tt.log 2>&1

  ./testreport -MPI 3 -ur4 -adm -of ../tools/build_options/linux_amd64_ifort11 \
   -devel -q -match 5 -a jmc@mitgcm.org >> ../../tr_run_$tt.log 2>&1

  sed -n "/ email /,/^======== End of testreport / p" ../../tr_run_$tt.log
;;

'imp2')

  export OMP_NUM_THREADS=2
  export KMP_STACKSIZE=400m

  ./testreport -MPI 2 -mth -of ../tools/build_options/linux_amd64_ifort11 \
   -devel -nc -repl_mk do_make_syntax.sh -obj -dd > ../../tr_run_$tt.log 2>&1
  echo '' >> ../../tr_run_$tt.log 2>&1

  ./testreport -MPI 2 -mth -of ../tools/build_options/linux_amd64_ifort11 \
   -devel -q -a jmc@mitgcm.org >> ../../tr_run_$tt.log 2>&1

  sed -n "/ email /,/^======== End of testreport / p" ../../tr_run_$tt.log

  #- test restart:
  echo '' >> ../../tr_run_$tt.log 2>&1
  ../tools/do_tst_2+2 -mpi -a jmc@mitgcm.org >> ../../tr_run_$tt.log 2>&1
;;

'iur4')

  ./testreport -MPI 3 -ur4 -of ../tools/build_options/linux_amd64_ifort11 \
   -devel -nc -repl_mk do_make_syntax.sh -obj -dd > ../../tr_run_$tt.log 2>&1
  echo '' >> ../../tr_run_$tt.log 2>&1

  ./testreport -MPI 3 -ur4 -of ../tools/build_options/linux_amd64_ifort11 \
   -devel -q -match 5 -a jmc@mitgcm.org >> ../../tr_run_$tt.log 2>&1

  sed -n "/ email /,/^======== End of testreport / p" ../../tr_run_$tt.log

  #- test restart:
  echo '' >> ../../tr_run_$tt.log 2>&1
  ../tools/do_tst_2+2 -mpi -a jmc@mitgcm.org >> ../../tr_run_$tt.log 2>&1
;;

'gadm')

  ./testreport -MPI 3 -adm -of ../tools/build_options/linux_amd64_gfortran \
   -devel -ncad -nc -a jmc@mitgcm.org >> ../../tr_run_$tt.log 2>&1

  sed -n "/ email /,/^======== End of testreport / p" ../../tr_run_$tt.log
;;

'gads')

  ./testreport -adm -of ../tools/build_options/linux_amd64_gfortran \
   -devel -ncad -nc -a jmc@mitgcm.org >> ../../tr_run_$tt.log 2>&1

  sed -n "/ email /,/^======== End of testreport / p" ../../tr_run_$tt.log
;;

'gad4')

  ./testreport -adm -ur4 -of ../tools/build_options/linux_amd64_gfortran \
   -devel -ncad -nc -match 5 -a jmc@mitgcm.org >> ../../tr_run_$tt.log 2>&1

  sed -n "/ email /,/^======== End of testreport / p" ../../tr_run_$tt.log
;;

'gmp2')

  export OMP_NUM_THREADS=2
  export GOMP_STACKSIZE=400m

  ./testreport -MPI 2 -mth -of ../tools/build_options/linux_amd64_gfortran \
   -devel -nc -a jmc@mitgcm.org >> ../../tr_run_$tt.log 2>&1

  sed -n "/ email /,/^======== End of testreport / p" ../../tr_run_$tt.log

  #- test restart:
  echo '' >> ../../tr_run_$tt.log 2>&1
  ../tools/do_tst_2+2 -mpi -a jmc@mitgcm.org >> ../../tr_run_$tt.log 2>&1
;;

'gmpi')

  ./testreport -MPI 3 -of ../tools/build_options/linux_amd64_gfortran \
   -devel -nc -a jmc@mitgcm.org >> ../../tr_run_$tt.log 2>&1

  sed -n "/ email /,/^======== End of testreport / p" ../../tr_run_$tt.log

  #- test restart:
  echo '' >> ../../tr_run_$tt.log 2>&1
  ../tools/do_tst_2+2 -mpi -a jmc@mitgcm.org >> ../../tr_run_$tt.log 2>&1
;;

'gmp4')

  ./testreport -MPI 3 -ur4 -of ../tools/build_options/linux_amd64_gfortran \
   -devel -nc -match 5 -a jmc@mitgcm.org >> ../../tr_run_$tt.log 2>&1

  sed -n "/ email /,/^======== End of testreport / p" ../../tr_run_$tt.log

  #- test restart:
  echo '' >> ../../tr_run_$tt.log 2>&1
  ../tools/do_tst_2+2 -mpi -a jmc@mitgcm.org >> ../../tr_run_$tt.log 2>&1
;;

'gfo')

  ./testreport -of ../tools/build_options/linux_amd64_gfortran \
   -devel -nc -a jmc@mitgcm.org >> ../../tr_run_$tt.log 2>&1

  sed -n "/ email /,/^======== End of testreport / p" ../../tr_run_$tt.log

  #- test restart:
  echo '' >> ../../tr_run_$tt.log 2>&1
  ../tools/do_tst_2+2 -a jmc@mitgcm.org >> ../../tr_run_$tt.log 2>&1
;;

'gfo4')

  ./testreport -ur4 -of ../tools/build_options/linux_amd64_gfortran \
   -devel -nc -match 5 -a jmc@mitgcm.org >> ../../tr_run_$tt.log 2>&1

  sed -n "/ email /,/^======== End of testreport / p" ../../tr_run_$tt.log

  #- test restart:
  echo '' >> ../../tr_run_$tt.log 2>&1
  ../tools/do_tst_2+2 -a jmc@mitgcm.org >> ../../tr_run_$tt.log 2>&1
;;

'g77')

  ./testreport -of ../tools/build_options/linux_amd64_g77 \
   -skd 'fizhi-cs-32x32x40 fizhi-cs-aqualev20' \
   -nc -a jmc@mitgcm.org >> ../../tr_run_$tt.log 2>&1

  sed -n "/ email /,/^======== End of testreport / p" ../../tr_run_$tt.log

  #- test restart:
  echo '' >> ../../tr_run_$tt.log 2>&1
  ../tools/do_tst_2+2 -a jmc@mitgcm.org >> ../../tr_run_$tt.log 2>&1
;;

*) echo "unrecognized test suffix '$tt' <== skipped" ;;
esac

  set +x
  cd ../..

 else
  echo "error: missing dir MITgcm_$tt/verification"
 fi

done
